cd /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy
# alignment rep 1
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R1-000.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R1-000.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R1-100.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R1-100.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R1-025.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R1-025.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R1-050.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R1-050.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R1-075.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R1-075.bam
# alignment rep 2
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R2-000.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R2-000.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R2-100.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R2-100.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R2-025.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R2-025.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R2-050.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R2-050.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R2-075.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R2-075.bam
# alignment rep 3
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R3-000.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R3-000.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R3-100.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R3-100.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R3-025.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R3-025.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R3-050.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R3-050.bam
subread-align -t 0 -T 12 -i /wehisan/home/allstaff/d/dong.x/personal/index/hg19/hg19_index -r /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R3-075.fastq.gz -o /stornext/General/data/user_managed/grpu_mritchie_1/Mixture/MainStudy/R3-075.bam