---
title: "DESeq2"
author: "Xueyi Dong"
date: "26/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DESeq2)
```

```{r}
fc <- readRDS("counts_ONT.RDS")
dds <- DESeqDataSetFromMatrix(countData=  fc$counts[,1:6], 
                              colData = data.frame(
                                group = rep(c("H1975", "HCC827"), c(3,3))
                              ),
                              design = ~group)
keep <- rowSums(counts(dds)) > 1 & rowSums(counts(dds) >= 10) >= 3
dds <- dds[keep,]
nrow(dds)

human.gene <- grep("^ENSG", rownames(dds))
sequin.gene <- grep("^R", rownames(dds))
dds.human <- dds[human.gene, ]
dds.sequin <- dds[sequin.gene, ]
```

```{r}
dds.human <- DESeq(dds.human)
dds.sequin <- DESeq(dds.sequin)
res.human <- results(dds.human)
res.sequin <- results(dds.sequin)
```

```{r}
res.sequin <- as.data.frame(res.sequin)
anno <- read.table("/wehisan/home/allstaff/d/dong.x/annotation/sequins/rnasequin_genes_2.4.tsv", header = TRUE, stringsAsFactors = FALSE)
anno$logFC <- log(anno$MIX_B / anno$MIX_A)

res.sequin$logFC_expected <- anno$logFC[match(rownames(res.sequin), anno$NAME)]
res.sequin$LENGTH <- anno$LENGTH[match(rownames(res.sequin), anno$NAME)]
cor(res.sequin$log2FoldChange, res.sequin$logFC_expected)

res.sequin$isDE <- res.sequin$logFC_expected!=0
# Test FDR
table(res.sequin$isDE, res.sequin$padj<0.05)
```

