# source("/wehisan/home/allstaff/d/dong.x/analysis/2020/smchd1/NSC/QC/func.R")
suppressPackageStartupMessages({
  library(ShortRead)
  library(GenomicAlignments)
  library(dplyr)
  library(ggplot2)
  library(data.table)
  library(GenomicFeatures)
  library(Hmisc)
  library(edgeR)
})


# #--------------
# # read in single readDF
dir <- "/stornext/General/data/user_managed/grpu_mritchie_1/XueyiDong/long_read_benchmark/ONT/QC/readDF"
args = commandArgs(trailingOnly=TRUE)
i = as.numeric(args[1])
RDFs <- list.files(path = dir, pattern="RDS$")
Sys.time()
cat("reading RDF", RDFs[i], "\n")
readDF <- readRDS(file.path(dir, RDFs[i]))
Sys.time()
cat("RDF loaded.", "\n")
gc()
Sys.time()

tx <- unique(readDF$seqnames)
cat("A total of", length(tx),"tx", "\n")
txStat <- sapply(tx, function(x){
  # cat("calculating for", substring(x, 1,17), "\n")
  sel = which(readDF$seqnames==x)
  meanCovFrac = mean(readDF[sel, ]$covFraction)
  medianCovFrac = median(readDF[sel, ]$covFraction)
  fl95 = sum(readDF[sel, ]$covFraction >= 0.95) / length(sel)
  fl90 = sum(readDF[sel, ]$covFraction >= 0.90) / length(sel)
  # cat(substring(x, 1,17),  "length:", readDF[sel[1], "tx_len"], ", FL count:", fl95, "\n")
  return(c(x, readDF[sel[1], "tx_len"], meanCovFrac, medianCovFrac, fl95, fl90, length(sel)))
}, simplify=TRUE)
Sys.time()
cat("saving intermediate output result.", "\n")
saveRDS(txStat, paste0("txStat/byTx/txStatRaw", i, ".RDS"))
rm(readDF)
cat("clean memory.", "\n")
gc()
Sys.time()
cat("transformming tx stats.", "\n")
txStat <- as.data.frame(t(txStat))
colnames(txStat) <- c("tx", "tx_len", "mean", "median", "fl95", "fl90", "count")
gc()
Sys.time()
cat("calculation completed.", "\n")
saveRDS(txStat, paste0("txStat/byTx/txStat", i, ".RDS"))
